# Generated by Django 3.2.8 on 2021-10-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='timezone',
        ),
    ]
